### ISSUE TITLE
Change "life" member to "club"

### ISSUE THREAD

**Issue by Dave748yel** [joeFischetti/GasPump#7]
Please change the entry of a life member to "Club". This is so we can establish a price for gas for club use like the lawn mower. If we create a member type that simply replaces the life member which we don't need, with, "club" that will allow me to change the price for the club. Then I created a user called "club club" and we can select the member type for that user to be club.

**Comment by joeFischetti** [comment]
changed and uploaded.  Let me know if thats okay.
I did it before reading the comment (I just read to the title), so i changed it to "club member" instead of simply "club".  I can fix if necessary.

**Comment by Dave748yel** [comment]
Joe,
If you could change it to just, "club" that would be ideal. 

Did you have any difficulty with TeamViiewer?  

Dave Messina
Malden on Hudson, New York
Dmessina@hvc.rr.com
Mobile: 914-646-5258

**Comment by joeFischetti** [comment]
Okay, I'll change it today.

No issues. I've used TeamViewer for some time at work.


On Mar 25, 2017 6:39 AM, "Dave748yel" <notifications@github.com> wrote:

Joe,
If you could change it to just, "club" that would be ideal.

Did you have any difficulty with TeamViiewer?

Dave Messina
Malden on Hudson, New York
Dmessina@hvc.rr.com
Mobile: 914-646-5258 <(914)%20646-5258>

> On Mar 25, 2017, at 12:55 AM, Joe Fischetti <notifications@github.com>
wrote:
>
> changed and uploaded. Let me know if thats okay.
> I did it before reading the comment (I just read to the title), so i
changed it to "club member" instead of simply "club". I can fix if
necessary.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/joeFischetti/GasPump/issues/7#issuecomment-289203628>,
or mute the thread

**Comment by joeFischetti** [comment]
Should be all set up, It's live on the machine.

**Comment by Dave748yel** [comment]
Joe, 
I was watching you work.  It’s other worldly to see a PC next to you start to have someone work on it.

Thank you!  I do believe this is all set!

I need to create a user and I want to boot to that no-password user.  And, I want to keep the admin ID to myself.  I’m sure I can create a new account.  I do I have Win10 boot to that account?

Thanks again.  This is fantastic work.


Dave
